### ISSUE TITLE
Support pages under app/pages

### ISSUE THREAD

**Issue by kumosal** [vinissimus/next-translate#675]
Hello,

I'm trying next-translate for a multilingual site using BlitzJS. Although, Blitzjs is based on Nextjs, I couldn't get it to work because in Blitz pages can be created in more places not just in the default top level folders /pages or /src/pages:
[BlitzJs default folders](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/build/utils.ts#L54-L59)
`export const topLevelFoldersThatMayContainPages = [
  'pages',
  'src',
  'app',
  'integrations',
]`

It would be useful if we could have an option to add top level folders that may contain pages. For BlitzJs devs, they would just simply define folders they use for pages in the i18n.json file. Is that possible?

**Comment by iDavidB** [comment]
Wasn't this discussed in https://github.com/vinissimus/next-translate/issues/499 and fixed in https://github.com/vinissimus/next-translate/pull/505?

**Comment by aralroca** [comment]
@kumosal If the fix we made works then I will close the issue. Comment if it doesn't work and report it and then we will reopen it. Thanks, @iDavidB to remember it!

**Comment by kumosal** [comment]
still it doesn't work like in nextjs. it works only if I change this line to:
const pagesPath = path.join(dir, arePagesInsideSrc ? '/src/pages' : '/pages')
to: 
const pagesPath = path.join(dir, arePagesInsideSrc ? '/src/pages' : '/**app**/pages')

now next-translate can translate pages under "/app/pages",

**Comment by aralroca** [comment]
now next-translate can translate pages under "/app/pages"? Ok, I didn't know it. So in this case we need to fix it. Thanks to report it.

**Comment by aralroca** [comment]
@kumosal did you try `NEXT_TRANSLATE_PATH='./app' yarn dev`?
`

**Comment by aralroca** [comment]
Already fixed in [1.1.1-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.1.1-canary.2), it should work without any change. It looks first `src` then `app` and then `integrations`. Also, I add the config variable `pagesInDir` to support cases as defined on https://github.com/vinissimus/next-translate/issues/682

**Comment by flybayer** [comment]
@aralroca this doesn't fully fix Blitz support, because blitz supports multiple different pages folders throughout the codebase (not just a single pages folder). I see you need pages folder for reading contents of `_app`. Do you need to manually read pages for anything else?

**Comment by edmbn** [comment]
@aralroca Ye

> @flybayer you can pass the `pagesInDir` in the `i18n.js` configuration file
> 
> https://github.com/vinissimus/next-translate/blob/master/src/plugin/index.ts#L18
> 
> And is only need it to know if exist an `_app.js` or not, and if this `_app.js` has a `getInitialProps`. Because it changes the behavior of the loader.

Yes but in Blitz we can have multiple /pages folders, not only one. pagesInDir should be an array, not a string right?
